version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: apache
     group: apache
     mode: 777
     type:
       - file
