version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
permissions:
   - object: /home/ec2-use
     pattern: "**"
     owner: naman
     group: naman
     mode: 777
     type:
       - file
