version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: /home/ec2-user/scripts/install_dependencies
      timeout: 300
      runas: root
    - location: /home/ec2-user/scripts/scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /home/ec2-user/scripts/scripts/stop_server
      timeout: 300
      runas: root
